name: Pylint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint anybadge

      - name: Run pylint and capture score
        id: pylint
        run: |
          # Run pylint and capture the overall score from the output.
          # The output line typically looks like:
          # "Your code has been rated at 9.63/10"
          score=$(pylint $(git ls-files '*.py') --score=y --exit-zero | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
          echo "pylint_score=$score" >> $GITHUB_OUTPUT

      - name: Generate pylint badge using anybadge
        run: |
          # Generate a badge using anybadge and save it to the /docs folder.
          # Thresholds: score < 2 -> red, < 4 -> orange, < 8 -> yellow, < 10 -> green.
          anybadge --label=pylint --value=${{ steps.pylint.outputs.pylint_score }} --file=docs/pylint.svg 2=red 4=orange 8=yellow 10=green

      - name: Commit updated badge to docs directory
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update pylint badge"
          add: "docs/pylint.svg"
          commit_author: "github-actions <github-actions@github.com>"
