name: Pylint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install git+https://github.com/blengerich/pylint-badge

    - name: Run Pylint and Generate Badge
      run: |
        pylint $(git ls-files '*.py') --fail-under 9.5 --fail-on E
        pylint-badge $(git ls-files '*.py') pylint.svg

    - name: Upload Pylint Badge Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint-badge
        path: docs/pylint.svg
