name: Code Quality CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint anybadge lizard

      - name: Run pylint and capture score
        id: pylint
        run: |
          score=$(pylint $(git ls-files '*.py') --score=y --exit-zero | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
          echo "pylint_score=$score" >> $GITHUB_OUTPUT

      - name: Run lizard and capture average complexity
        id: lizard
        run: |
          complexity=$(lizard . | grep -E "^[[:space:]]*[0-9]+" | tail -n 1 | awk '{print $3}')
          echo "complexity=$complexity" >> $GITHUB_OUTPUT

      - name: Create docs folder
        run: mkdir -p docs

      - name: Generate pylint badge using anybadge
        run: |
          anybadge --overwrite --label=pylint --value=${{ steps.pylint.outputs.pylint_score }} --file=docs/pylint.svg 2=red 4=orange 8=yellow 10=green

      - name: Generate complexity badge using anybadge
        run: |
          anybadge --overwrite --label=complexity --value=${{ steps.lizard.outputs.complexity }} --file=docs/complexity.svg 5=green 10=yellow 15=orange 20=red

      - name: Commit updated badges to docs directory
        uses: EndBug/add-and-commit@v9
        with:
          message: "update pylint and complexity badges"
          add: "docs/pylint.svg docs/complexity.svg"
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
